# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "installing dependencies necessary for tauri"
    init: |
      DEBIAN_FRONTEND=noninteractive apt-get install keyboard-configuration
      sudo apt update
      sudo apt -y install libwebkit2gtk-4.0-dev \
      build-essential \
      libssl-dev \
      libgtk-3-dev \
      libappindicator3-dev