# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: "installing dependencies necessary for tauri"
    init: |
      sudo apt update
      DEBIAN_FRONTEND=noninteractive sudo apt-get -y install libwebkit2gtk-4.0-dev \
      build-essential \
      libssl-dev \
      libgtk-3-dev \
      libappindicator3-dev \
      librsvg2-dev